---
format_version: 10
pipelines:
  node-microservice:
    group: microservice
    materials:
      gitrepo:
        git: https://github.com/Sliceem/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building app"
