---
format_version: 10
common:
  deploy-task: &deploy-task
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Building ${ENV_NAME} environment"
pipelines:
  node-microservice:
    group: microservice
    materials:
      gitrepo:
        git: https://github.com/Sliceem/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building app"
      - deploy-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            build:
              tasks: *deploy-task
      - test-dev:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing DEV"
      - deploy-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            build:
              tasks: *deploy-task
      - test-int:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing INT"
      - deploy-prod:
          environment_variables:
            ENV_NAME: PROD
          jobs:
            build:
              tasks: *deploy-task
      - test-prod:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing PROD"
