---
format_version: 10
pipelines:
  node-microservice:
    group: microservice
    materials:
      gitrepo:
        git: git@github.com:Sliceem/ci_course.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building app"
